
GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/find/adama12_h_ayxn


###
GET  http://localhost:3000/api/news/latest-news
Content-Type: application/json


###
GET  http://localhost:3000/api/news/fetch-news
Content-Type: application/json


###
POST http://localhost:3000/api/news/add-news
Content-Type: application/json

{
   "title": "Green plant is a great way to experiement the future",
   "description": "this is green plant discription",
   "newsImg": "../src/assets/profilePictures/img-1.jpg"
}
###
GET http://localhost:3000/projects/fetchProject
Content-Type: application/json
###

POST http://localhost:3000/projects/addProject
Content-Type: application/json

{
   "title": "first project title",
   "description": "eeeeeeeeekeowoi euieinreo eorewon eeone lwl",
   "projectImg": "../src/assets/profilePictures/img-7.jpg"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username":"abraham", 
    "email":"ab@gmail.com", 
    "role":"admin", 
    "password": "abraham"
}

###
GET http://localhost:3000/



###
POST http://localhost:3000/api/auth/login
Content-Type: application/json
 
{
   "email": "adama@gmail.com",
   "password": "adama"
}


###
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
 
