
###
GET http://localhost:3000/api/news/eginews?egid=bb6ecb84-5d09-42ba-994b-67d238887df2
###
GET http://localhost:3000/api/news/
###
GET http://localhost:3000/api/news/latestNews

###
POST http://localhost:3000/api/news
Content-Type: application/json

{
    "title": "The Environment is clean",
    "description": "Environemt is the best here",
    "category": "Ecosystem",
    "newsImg": "uuuuu"
}



###

POST http://localhost:3000/api/upload
# Content-Type: application/json



{
   "image": "../src/assets/logo.png"
}
###

POST http://localhost:3000/api/user
Content-Type: application/json

{
   "username": "massa",
   "email": "massa@gmail.com", 
   "password": "massa",
   "role": "admin",
   "profile": ""
}

###
GET http://localhost:3000/api/getusers
Content-Type: application/json



  
###
GET  http://localhost:3000/api/news/latest-news?quer
Content-Type: application/json


###
GET  http://localhost:3000/api/news/singlenews?id=1
Content-Type: application/json
###
GET  http://localhost:3000/api/news/fetch-news/search?s=movies
Content-Type: application/json



###
GET  http://localhost:3000/api/news/getnews
Content-Type: application/json


###
POST http://localhost:3000/api/news/add-news
Content-Type: application/json

{
   "title": "5th project News Title",
   "description": "this is our fifth project description",
   "category": "climite action 2025",
   "newsImg": "../src/assets/react.svg"
}

###
GET http://localhost:3000/api/projects/fetchProject
Content-Type: application/json

### Pagination route
GET http://localhost:3000/api/projects/project?item=3&page=2
Content-Type: application/json
###
GET http://localhost:3000/api/projects/latest-projects
Content-Type: application/json
###

POST http://localhost:3000/api/project
Content-Type: application/json

{
   "title": "Project eleven",
   "description": "Description of the fifth project",
   "projectImg": "./src/assets/03a6acdf091c4972ac8bcc3e65d010de.jpg"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username":"mohammed", 
    "email":"mohammed@gmail.com", 
    "role":"admin", 
    "password": ",mohammed"
}

###
GET http://localhost:3000/api/members/latest
###
GET http://localhost:3000/api/resource/latest-resources
###
GET http://localhost:3000/api/resource/full-resources



###
POST http://localhost:3000/api/auth/login
Content-Type: application/json
 
{
   "email": "abraham@gmail.com",
   "password": "abraham"
}


###
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
 
###
POST http://localhost:3000/upload
Content-Type: application/json
 

 {
   "profile" : "../src/assets/03a6acdf091c4972ac8bcc3e65d010de.jpg"
 }


###
GET http://localhost:3000/api/getusers
###
GET http://localhost:3000/api/links
###
POST http://localhost:3000/api/links
Content-Type: application/json


{
"menu_name":"activity logs", 
"link":"/users", 
"icon":"BiBroadcast",
"userRole": "super admin"
}
